version: '3'
services:
  linear:
    environment:
      PYTHONPATH: src/
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'linear'
    tty: true
    volumes:
      - .:/build/